/**
 * EffectHouseExporter
 *
 * Generates a downloadable .zip that a creator imports into the TikTok
 * Effect House desktop app and submits for review.
 *
 * What's in the zip:
 *  README.txt          — step-by-step import + submission instructions
 *  effect/main.js      — Effect House JavaScript that renders the widget
 *                        as a 2-D overlay on the camera feed
 *  effect/manifest.json — effect metadata (name, category, icon hint)
 *
 * Effect House JS API reference used:
 *   scene, FaceTracking, ScreenTransform, Component.MeshVisual, Material
 * The script is self-contained and documented so a creator can customise it.
 */
import { useState } from 'react';
import JSZip from 'jszip';
import { Download, Zap } from 'lucide-react';

interface Props {
  widgetName: string;
  widgetDescription: string;
  widgetCode: string;
}

// Generates the Effect House JavaScript.
// Effect House uses its own scene-graph API (no React/DOM), so we produce a
// hand-crafted overlay script that mirrors the visual style of the widget.
function generateEffectScript(name: string, description: string): string {
  const safeName = name.replace(/[^a-zA-Z0-9 ]/g, '').trim() || 'Pelada Widget';
  return `// ─────────────────────────────────────────────────────────────────────────
// TikTok Effect House — ${safeName}
// Generated by Pelada · pelada-plum.vercel.app
//
// HOW TO USE THIS FILE
// 1. In Effect House, create a new 2-D effect project.
// 2. Open the Scripting panel and replace the default script with this file.
// 3. In the Assets panel, import card.png (screenshot your Pelada widget).
// 4. Name the imported texture "pelada_card".
// 5. Hit Preview — your card will appear as an overlay on the camera feed.
// 6. Adjust CARD_SCALE and CARD_POSITION below to reposition it.
// 7. Submit via Effect House → Share → Submit for Review.
//
// Description: ${description || 'Football analytics widget'}
// ─────────────────────────────────────────────────────────────────────────

// ── Configuration — tweak these to position your card ──────────────────
var CARD_SCALE    = new vec2(0.55, 0.85); // width, height as fraction of screen
var CARD_POSITION = new vec2(0, -0.35);   // 0,0 = centre; negative Y = lower half
var CARD_OPACITY  = 0.94;
var SHOW_DURATION = 0;                    // 0 = always visible; >0 = auto-hide (seconds)
// ────────────────────────────────────────────────────────────────────────

var scene = global.scene;

// Create a Screen Image object that sits above the camera feed
var cardObject = scene.createSceneObject('PeladaCard');
var screenTransform = cardObject.createComponent('Component.ScreenTransform');
screenTransform.anchors.top    =  CARD_POSITION.y + CARD_SCALE.y / 2;
screenTransform.anchors.bottom =  CARD_POSITION.y - CARD_SCALE.y / 2;
screenTransform.anchors.left   =  CARD_POSITION.x - CARD_SCALE.x / 2;
screenTransform.anchors.right  =  CARD_POSITION.x + CARD_SCALE.x / 2;

var meshVisual = cardObject.createComponent('Component.MeshVisual');
meshVisual.mesh = scene.assets.find('PlaneMesh');

// Assign the imported card texture
var cardTexture = scene.assets.find('pelada_card');
if (cardTexture) {
  var mat = scene.assets.find('UnlitBlendedMaterial').clone();
  mat.mainPass.baseTex = cardTexture;
  mat.mainPass.baseColor = new vec4(1, 1, 1, CARD_OPACITY);
  meshVisual.addMaterial(mat);
}

// Optional: pulse animation to draw attention
var elapsed = 0;
var scriptComponent = cardObject.createComponent('Component.ScriptComponent');
scriptComponent.createEvent('UpdateEvent').bind(function(eventData) {
  elapsed += eventData.getDeltaTime();
  var pulse = 1 + 0.04 * Math.sin(elapsed * 3.5);
  screenTransform.scale = new vec3(pulse, pulse, 1);

  // Auto-hide after SHOW_DURATION seconds (if > 0)
  if (SHOW_DURATION > 0 && elapsed > SHOW_DURATION) {
    cardObject.enabled = false;
  }
});

print('[Pelada] Effect loaded — ${safeName}');
`;
}

function generateManifest(name: string, description: string): string {
  return JSON.stringify({
    name: name || 'Pelada Widget',
    description: description || 'Football analytics overlay — generated by Pelada',
    category: 'Sports',
    tags: ['football', 'analytics', 'pelada', 'sports', 'wwc2027'],
    minEffectHouseVersion: '2.0.0',
    generatedBy: 'Pelada (pelada-plum.vercel.app)',
    instructions: 'Import this project folder into TikTok Effect House. See README.txt.',
  }, null, 2);
}

function generateReadme(name: string, embedUrl: string): string {
  return `╔═══════════════════════════════════════════════════════════════╗
║           PELADA → TIKTOK EFFECT HOUSE                        ║
║           Generated for: ${(name || 'My Widget').padEnd(35)}║
╚═══════════════════════════════════════════════════════════════╝

WHAT YOU HAVE
─────────────
  effect/main.js        Effect House script (overlay logic)
  effect/manifest.json  Effect metadata
  README.txt            This file

STEP-BY-STEP IMPORT
────────────────────
1. Download & install TikTok Effect House (effecthouse.tiktok.com)
2. Open Effect House → New Project → "2D Effect (Camera)"
3. In the Assets panel: Import Image → select a SCREENSHOT of your
   Pelada widget (visit the link below, screenshot it, rename to card.png)
4. Name the imported asset exactly: pelada_card
5. Open the Scripting panel (top bar) → clear the default script
6. Paste the contents of effect/main.js
7. Adjust CARD_SCALE and CARD_POSITION at the top of the script
   to reposition the card on screen
8. Click Preview → test it on your device
9. Click Share → Submit for Review
10. Review typically takes 1-4 business days

YOUR PELADA WIDGET LINK (screenshot this for the card texture)
──────────────────────────────────────────────────────────────
${embedUrl}

TIPS
────
• Use your phone's screenshot + crop tool to get a clean card image
• For the GOAT Builder card: screenshot just the card section
• For Lineup Validator: screenshot the full pitch view
• Vertical (9:16) crops work best for TikTok
• The effect auto-pulses to draw viewer attention

SUPPORT
───────
Questions? Open an issue at github.com/jessicafan3ck/Pelada
`;
}

export default function EffectHouseExporter({ widgetName, widgetDescription, widgetCode }: Props) {
  const [loading, setLoading] = useState(false);
  const [done, setDone]       = useState(false);

  const exportZip = async () => {
    setLoading(true);
    try {
      const embedBase = 'https://pelada-plum.vercel.app';
      // Re-encode the widget code for the embed URL
      const bytes = new TextEncoder().encode(widgetCode);
      let binary = '';
      bytes.forEach(b => { binary += String.fromCharCode(b); });
      const embedUrl = `${embedBase}/?embed=${btoa(binary)}`;

      const zip = new JSZip();
      zip.file('README.txt', generateReadme(widgetName, embedUrl));
      const effectFolder = zip.folder('effect')!;
      effectFolder.file('main.js',        generateEffectScript(widgetName, widgetDescription));
      effectFolder.file('manifest.json',  generateManifest(widgetName, widgetDescription));

      const blob = await zip.generateAsync({ type: 'blob', compression: 'DEFLATE' });
      const a = document.createElement('a');
      a.href = URL.createObjectURL(blob);
      a.download = `${(widgetName || 'pelada-widget').replace(/\s+/g, '-').toLowerCase()}-effect-house.zip`;
      a.click();
      URL.revokeObjectURL(a.href);
      setDone(true);
      setTimeout(() => setDone(false), 3000);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="rounded-2xl border border-yellow-500/20 bg-yellow-500/5 p-5 space-y-3">
      <div className="flex items-start gap-3">
        <div className="p-2 bg-yellow-500/10 rounded-lg shrink-0">
          <Zap className="w-5 h-5 text-yellow-400" />
        </div>
        <div>
          <h3 className="text-sm font-bold text-white">Export for TikTok Effect House</h3>
          <p className="text-xs text-zinc-500 mt-1 leading-relaxed">
            Downloads a <code className="text-yellow-400">.zip</code> you import directly into the Effect House
            desktop app. Includes the overlay script, manifest, and a step-by-step README.
            TikTok review takes 1–4 days.
          </p>
        </div>
      </div>

      {/* Steps */}
      <ol className="text-[11px] text-zinc-500 space-y-1 pl-4 list-decimal">
        <li>Download the zip below</li>
        <li>Screenshot your widget (open the embed URL on your phone)</li>
        <li>Import screenshot as <code className="text-yellow-400">pelada_card</code> texture in Effect House</li>
        <li>Paste <code className="text-yellow-400">effect/main.js</code> into the Scripting panel</li>
        <li>Preview → Submit for review</li>
      </ol>

      <button
        onClick={exportZip}
        disabled={loading || !widgetCode}
        className="w-full py-2.5 rounded-xl bg-yellow-500/15 border border-yellow-500/30 text-yellow-400 hover:bg-yellow-500/25 transition-all text-xs font-bold disabled:opacity-40 disabled:cursor-not-allowed flex items-center justify-center gap-2"
      >
        {loading ? (
          <><div className="w-3.5 h-3.5 border-2 border-yellow-400/30 border-t-yellow-400 rounded-full animate-spin" /> Packaging…</>
        ) : done ? (
          '✓ Downloaded!'
        ) : (
          <><Download className="w-3.5 h-3.5" /> Download Effect House Package</>
        )}
      </button>
    </div>
  );
}
